### ISSUE TITLE
dependencies for de.vandermeer:svg2vector:jar missing

### ISSUE THREAD

**Issue by jason-s** [vdmeer/svg2vector#1]
```
[ERROR] Failed to execute goal on project svg2vector: Could not resolve dependencies for project de.vandermeer:svg2vector:jar:1.0.2: Could not find artifact de.vandermeer:skb-base:jar:0.1.0-SNAPSHOT -> [Help 1]
```

**Comment by vdmeer** [comment]
Ooops. commits for testing did go to master, should have been dev (never created dev though). Did update, should work now with 1.0.3 or 1.0.3-1 (either should work). Pushed new artifact to Maven, will be picked up by central whenever Sonatype is synced again.

Thanks!
/sven
